version: '3.8'

services: 
  selenium-hub:
    image: selenium/hub:4.17.0-20240123
    container_name: 'selenium-hub'
    volumes:
      - ./config.toml:/opt/bin/config.toml
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - selenium-grid
  
  firefox:
    image: selenium/node-firefox:122.0-geckodriver-0.34.0-grid-4.17.0-20240123
    container_name: 'firefox'
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid
    depends_on:
      - selenium-hub

  edge:
    image: selenium/node-edge:120.0-edgedriver-120.0-grid-4.17.0-20240123
    container_name: 'edge'
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid
    depends_on:
      - selenium-hub

  chrome:
    image: selenium/node-chrome:120.0-chromedriver-120.0-grid-4.17.0-20240123
    container_name: 'chrome'
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid
    depends_on:
      - selenium-hub
     
networks:
  selenium-grid:
    name: selenium-grid
    driver: bridge
