version: '3.8'

services:
  script:
    build:
      context: .
      dockerfile: dockerfile
#    network_mode: host
    networks:
      - selenium-grid

networks:
  selenium-grid:
    name: selenium-grid
    driver: bridge
