version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.18.0-20240220
    container_name: 'selenium-hub'
    volumes:
      - ./hub-config/config.toml:/opt/bin/config.toml
    environment:
      - host:0.0.0.0
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh"]
      interval: 15s
      timeout: 30s
      retries: 5
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - selenium-grid
        
  docker-node:
    image: selenium/node-docker:4.18.0-20240220
    volumes:
      - ./node-config/config.toml:/opt/bin/config.toml
      - ./node-config/assets:/opt/selenium/assets
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid

networks:
  selenium-grid:
    name: selenium-grid
    driver: bridge